### ISSUE TITLE
Crash on android trackAppLaunch

### ISSUE THREAD

**Issue by feoktistov** [AppsFlyerSDK/Unity#31]
After updating to the latest version of AppsFlyerSDK Unity on some devices we've received crash report after call trackAppLaunch in AppsFlyer.cs:
I/Unity   ( 2432): Exception: No such proxy method: UnityEngine.AndroidJavaRunnableProxy.toString()
I/Unity   ( 2432):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
I/Unity   ( 2432):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>:0 
I/Unity   ( 2432):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in <filename unknown>:0 

OS version:
Android 5.0, 5.0.1, 5.0.2
Device models:
Micromax Micromax AQ5001
LENOVO Lenovo TAB 2 A7-30HC
BeeTabPro Beeline Tab Pro
LENOVO Lenovo A5000
LGE LG-X155

On other devices there are no crashes.

**Comment by AppsFlyerGit** [comment]
Fixed, try with latest

**Comment by hajimeku** [comment]
Hey,

I have noticed this issue aswell since we updated the appsflyer sdk to latest sdk.

Exception: No such proxy method: UnityEngine.AndroidJavaRunnableProxy.toString()
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs)

Android OS 5.0 / API-21 (LRX21M/1438451071)
Android OS 5.0.1 / API-21 (LRX21M/1437138835)
Android OS 5.0.1 / API-21 (LRX21M/Lenovo_TB3-710F_S000027)
Android OS 5.0.1 / API-21 (LRX21M/vE2N-0)
Android OS 5.0.1 / API-21 (LRX22C/1436322340)
Android OS 5.0.1 / API-21 (LRX22C/1440151658)
Android OS 5.0.1 / API-21 (LRX22C/1440984936)
Android OS 5.0.2 / API-21 (LRX21M/1469766377)
Android OS 5.0.2 / API-21 (LRX22G/1446196001)
Android OS 5.0.2 / API-21 (LRX22G/1452240707)

Any idea why this may happen? I have changed a few things..
I removed the support library because we have this line in the gradle build script ..
"compile 'com.android.support:design:24.0.0'..
We use the 24.0.0 version because of firebase.

any suggestions?
